# -*- coding: utf-8 -*-
"""SalesDataAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OVRVLv-rchLHNrAzmorgQm7k7ZcUai6w
"""

import pandas as pd
df=pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSZ5GNRsA_kRcBUyavuXaNQIkEXi6AS7fUgITWFE7QF0JfQxlk1hYgGSi6jHKUmYm0HAQWSlIyn2svH/pub?output=csv')

print("Total orders in June is:", df.shape[0])

df=df[0:6792]

display(df[df['Item Customization']!='Nan'])

df=df.drop_duplicates()

df.size

df.info()

df

df['Quantity']=df['Quantity'].astype(float)
df['Price']=df['Price'].astype(float)
df['Customization Price']=df['Customization Price'].astype(float)
df['Packing Charge']=df['Packing Charge'].astype(float)
df['GST on Packing Charge']=df['GST on Packing Charge'].astype(float)
df['Delivery Charge']=df['Delivery Charge'].astype(float)
###############################################
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")
df['Order Time'] = pd.to_datetime(df['Order Time'], format='%I:%M:%S %p').dt.time
df['Hour'] = pd.to_datetime(df['Order Time'], format='%H:%M:%S').dt.hour



df.info()

df

df.groupby('DOW').aggregate({'Final Price':'sum','Order ID':'nunique'})

df.groupby('Hour').aggregate({'Final Price':'sum','Order ID':'nunique'})

df.groupby('OrderType').aggregate({'Final Price':'sum','Order ID':'nunique'})

len(df['ItemName'])

df.groupby('ItemName').aggregate({'Final Price':'sum','Order ID':'nunique'})

df.groupby('Date').aggregate({'Final Price':'sum','Order ID':'nunique'})

df.groupby('Order Platform').aggregate({'Final Price':'sum','Order ID':'nunique'})

df1=df[['ItemName','Order ID']]

df2=df1.explode('ItemName')

df2.groupby('ItemName').aggregate({'Order ID':'nunique'})

df['WeekNumber']= df['Date'].dt.isocalendar().week

df.info()

df['WeekNumber']

df['WeekNumber']=df['WeekNumber'].astype(str)

df.groupby('WeekNumber').aggregate({'Final Price':'sum','Order ID':'nunique'})

"""Multi Items"""



df2 = df.groupby('Order ID').agg({'ItemName': list, 'Final Price': 'sum'}).reset_index()

df2['ItemLength']=df2['ItemName'].apply(lambda x: len(x))

df2.info()

df2

df2=df2[df2["ItemLength"] >1]

df2

display(df2.groupby(df2['ItemName'].apply(pd.Series).stack().reset_index(drop=True))['Final Price'].sum())

df2['ItemName'] = df2['ItemName'].apply(lambda x: tuple(sorted(x)))

multi=df2.groupby('ItemName').aggregate({'Final Price':'sum','Order ID':'nunique'})

multi



# Sorting by column 'Country'
multi.sort_values(by=['Order ID'], ascending=False)

multi.to_csv('grouped_data.csv')

